pkg/container/dockerimpl/manager.go, pkg/container/dockerimpl/restart.go, pkg/container/dockerimpl/stop.go, pkg/container/manager.go
- `StopContainer()`関数や`RestartContainer()`関数を用いてコンテナの停止・再起動を実装
- タイムアウトは5秒に設定、定数に追加
close #8
=> アプリコンテナの停止・再起動の実装

img/Dockerfile
コンテナ環境
- ubuntu:20.10
- make,git,wget,unzip,curl
- nodejs
- yarn
- npm
- go:1.15.6
- python3
- pip
- rust
- cargo
- php
- composer
- java:openjdk-15
- gradle:6.7.1
- gcc 
- .NET 5
(:がついているものは直接バージョンを指定しているもの)
イメージサイズは大体2.8GBくらいです
unzip や curl等は使い終わったらアンインストールしておくべきでしょうか？
あとrustのdoc(.html)が400MBくらい使っているのですが、消したほうがいいのでしょうか？
あと結構読みにくいのですが、分けたほうがいいのでしょうか？
=> #5 汎用ベースイメージの作成

go.mod, pkg/container/dockerimpl/create.go, pkg/container/k8simpl/create.go, pkg/container/manager.go
- `CreateArgs`に`Envs`フィールドを実装
- それぞれのコンテナの`Create`関数を環境変数を追加するように変更
- `go mod tidy`
close #14
=> コンテナへの環境変数の指定を実装

pkg/builder/service.go, pkg/builder/task.go
- `progressui.DisplaySolveStatus()`の引数のcontextを`ctx`から`context.TODO()`に変更
- エラーの場合分けに`errors.Is(err, status.FromContextError(context.Canceled).Err())`をORで追加
close #44
=> BuildのCancel処理ができないバグの修正

Makefile, cmd/ns/main.go, docker-compose.yaml
とりあえず遊ぼうとしたら `docker compose up` が動かなかったので、（少なくとも自分の手元で）立ち上がるようにしました
- `go run ...` がコマンドの依存が無いよと言われて動かなかったので、go install する方式に
- 設定が足りていなくてそのままだと ns (api server) が立ち上がらなかったので、環境変数を追加
なにか困るものがあればコメントください :pray:
=> chores: fix dev env

dashboard/src/pages/apps.tsx
赤で囲った部分の値がリアクティブに反映されるようになりました。
@motoki317 
(https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/building-ui-with-components の最後の部分)
``But destructuring props is usually a bad idea in Solid. ...... When we destructure our props object in the function signature, we immediately access the object's properties and lose reactivity.`` らしくて、リアクティブ性じゃなくなっちゃうみたいなのでSolid.jsで書くときはpropsで入れるようにしましょう。
=> countAppsStatusの実装

dashboard/package.json
romeのバグで、yarn lint時に--applyがついている状況だとエラーの原因が出力されないため、--applyなしのlintを追加しておくことで確認できると思ったから
package.jsonのscriptsに "lint:noapply": "rome check src" を追加
https://q.trap.jp/messages/82a8ca7a-1521-4a96-aeeb-748d7fb695c6
=> package.jsonのscriptsに "lint:noapply": "rome check src" を追加

pkg/usecase/builder_service.go
resolves #523 
builderに `git submodule --init --recursive` 相当の処理を入れた
=> update submodules resolves #523

dashboard/src/components/Button.tsx
Buttonコンポーネントで使用可能なプロパティがハードコードされており、`onClick`と`disabled`のみが操作できるようになっていた。
#542 や #543 でのフォームの実装において、button要素の`type`プロパティを操作する必要があり(`type=submit`を使用できるとブラウザで用意されたバリデーションチェックを簡単に実装できるため)、button要素の標準プロパティを操作できるようにすることでこれを達成できるため。
- Buttonコンポーネントの受け付けるプロパティのinterfaceを`JSX.ButtonHTMLAttributes<HTMLButtonElement>`から継承させた
- Buttonコンポーネント内で`splitProps()`を使用して、独自に定義していた`color`, `size`プロパティと、それ以外のプロパティ(=`JSX.ButtonHTMLAttributes<HTMLButtonElement>`)の2つに分割し、後者をbutton要素のプロパティとして分割代入するようにした
- コンポーネントの型を定義するのに`ParentComponent<P>`を使用した
- コンポーネント設計の基本方針に従い、今後はsolid.jsで用意されたこれらの型を使用する
styled componentのvariantをpropsとして渡しているが(`color`, `size`)、これらの型はハードコーディングされたままになっています(styled componentの型がmacaron-cssでexportされておらず、おそらく独自に型パズルをしないといけない)。
- [`splitProps()` - …
=> Buttonコンポーネントでbutton要素の標準プロパティを使用できるように

api/proto/neoshowcase/protobuf/gateway.proto, dashboard/src/api/neoshowcase/protobuf/gateway_pb.ts, pkg/infrastructure/grpc/api_app_service.go, pkg/infrastructure/grpc/api_repository_service.go, pkg/infrastructure/grpc/pb/gateway.pb.go, pkg/infrastructure/repository/application.go, pkg/infrastructure/repository/artifact.go, pkg/infrastructure/repository/build.go, pkg/infrastructure/repository/git_repository.go, pkg/util/optional/of.go, pkg/util/optional/of_test.go
https://github.com/traPtitech/NeoShowcase/pull/548#discussion_r1212698655
Update(Application/Repository) ではid以外のフィールドがoptionalとして扱われるようにした
例外的に空文字は指定していないものとして扱われる (connect-go の limitation)
=> fix(breaking): Updateではフィールドはoptionalとして扱う

dashboard/src/components/AppNav.tsx, dashboard/src/components/UserAvatar.tsx, dashboard/src/components/UserSearch.tsx, dashboard/src/components/WebsiteSettings.tsx, dashboard/src/pages/apps/[id]/settings.tsx, dashboard/src/pages/repos/[id].tsx, dashboard/src/routes.tsx
ref: #484
- リポジトリオーナー設定と共通化
- アプリ情報ページ/ビルド一覧ページ/設定ページの切り替えボタンのデザイン修正
=> Add app setting page

pkg/usecase/apiserver/repository_service.go
fix: use system default if key id is left empty
=> システムデフォルト鍵でリポジトリ作成ができなくなっていた

dashboard/src/pages/apps/[id]/settings.tsx
アプリケーションのビルド設定項目において、ビルド/ランタイム種類を変更しなかった場合、DB, EntryPoint, Commandの変更が反映されていなかった
ページロード後のビルド設定の反映時の、`setBuildConfig`の引数の修正
3aeb8d131ce1dfb5dcf999ef89c5cd33d01bbaa6 と同一の原因だと思いますが、正直なぜこうなるのか仕様がつかみ切れていません、もう少し勉強します...
=> :bug: fix runtimeCofig to be changed

pkg/infrastructure/grpc/api_system_service.go, pkg/usecase/apiserver/app_service.go, pkg/usecase/apiserver/service.go, pkg/usecase/apiserver/system_service.go, pkg/usecase/cdservice/service.go, pkg/usecase/ssgen/generator.go, pkg/util/scutil/coalescer.go, pkg/util/scutil/once.go
system infoの読み込みをlazyにすることで、gatewayがすぐ立ち上がるようにする
=> fix: gateway server startup

cmd/ns-controller/wire_gen.go, pkg/domain/app.go, pkg/domain/app_build.go, pkg/domain/app_test.go, pkg/usecase/cdservice/service.go
今のままだとHashの計算に環境変数が考慮されていないから
Hashの計算で環境変数を考慮するようにした
closes https://github.com/traPtitech/NeoShowcase/issues/671
=> Hash計算に環境変数を含めるようにした

dashboard/src/components/Button.tsx, dashboard/src/components/Input.tsx, dashboard/src/components/RepositoryAuthSettings.tsx, dashboard/src/libs/clipboard.ts, dashboard/src/pages/apps/[id]/settings.tsx
resolve #627
- アプリ設定画面での環境変数コピーボタンの追加
- リポジトリ追加画面でのSSH公開鍵コピーボタンの追加
- `input`についていた不要なマージンの削除
- input自体に`margin-left`が付いており、縦並びでは問題なかったが横並びさせた時にデザインが崩れたため削除
- ツールチップ表示用に追加された`span`要素により、width="full"としたbutton/inputの幅が100%になっていなかったため修正
=> 環境変数/SSH公開鍵 コピーボタンの追加

pkg/infrastructure/grpc/cache_interceptor.go
`err != nil` の時 (`resp == nil` の時) にhashを計算しようとするとpanicする
panicするとerrの内容にかかわらず 500 Internal Server Error になってしまう
err をチェックする
=> CacheInterceptor: panicするのを修正

dashboard/src/components/templates/app/AppGeneralConfig.tsx, dashboard/src/libs/branchesSuggestion.ts
closes #831
ブランチ一覧の読込を遅延するようにし、エラーハンドリングを追加した
エラーメッセージが少しかっこ悪いかも?
=> /apps/:id/settingsでブランチ取得に失敗するとエラーが出ていた

dashboard/src/components/templates/app/WebsiteSettings.tsx
closes #875
部員認証方法選択ではラジオボタンコンポーネントが使用されている。
このラジオボタンコンポーネント自体はstring型の入力にしか対応していないため、enum(=number)で表されていたAuthenticationTypeを扱えるようにするため、認証方法変更時に変換処理を挟んでいる。
しかし、modular formsによって自動生成されるonChange関数なども一緒に設定されてしまっていたために、modular forms側での変換処理も実施されてしまい、設定値がNaNになってしまっていた。
modular fomrsによって自動作成されるcallback関数を削除することで、正しく動作するよう修正した。
=> 部員認証のラジオボタン切り替え時エラーの修正

pkg/infrastructure/repository/environment.go
環境変数を一度に複数設定するとdeadlockする
何回か `Save` を押せば一応ちゃんと保存される
application テーブルでロックをとるようにした
https://zenn.dev/shuntagami/articles/ea44a20911b817
=> 環境変数設定時にdeadlockするのを修正

pkg/usecase/builder/build_buildkit.go
close #877
`.dockerignore`が存在するなら名前を変更し、`Dockerifle`内でもとに戻す
[`.dockerignore`が存在するかの設定](https://github.com/moby/buildkit/blob/08180a774253a8199ebdb629d21cd9f378a14419/frontend/dockerui/namedcontext.go#L213)がbuildkitのコード内にありましたが、それを利用するとコードが複雑になりそうだったため、この方式にしました。
手元の開発環境で期待した通りに動作していることを確認しました
=> Commandビルドの場合は.dockerignoreを無視する

.local-dev/config/ns.yaml, cmd/config.go, pkg/infrastructure/backend/dockerimpl/backend_test.go, pkg/infrastructure/backend/dockerimpl/config.go, pkg/infrastructure/backend/dockerimpl/ingress.go, pkg/infrastructure/backend/k8simpl/backend_test.go, pkg/infrastructure/backend/k8simpl/config.go, pkg/infrastructure/backend/k8simpl/ingress.go
https://github.com/traefik/traefik/blob/e9bd2b45ac2bb1983fdee27d4efd76c450dfa338/pkg/muxer/http/mux.go#L53
traefik は priority が高いルートから検証していくため、大量にルートがあるとパフォーマンスが落ちる（かもしれない）
（計ってないので程度は知らない）
このようなときに特にアクセスが来ないルートのpriorityを下げるとパフォーマンス的に嬉しい
しかし、そもそもそこを気にするならtraefikインスタンスを分けるべきかも
どちらにしろ、ユーザーアプリの priority 値の制御はあると細かい制御ができて嬉しい
priorityOffset 設定を追加
https://doc.traefik.io/traefik/routing/routers/#priority
=> performance(backend): Add traefik rule priority offset

dashboard/src/components/templates/app/AppsFilter.tsx
closes #818
- Appsのフィルターの最大幅を`--kb-popper-content-available-width`で指定するようにした
- DropdownMenuコンポーネントに`fitViewport`(https://kobalte.dev/docs/core/components/dropdown-menu#dropdownmenu)propsがあるが、これを使うだけでは解決しなかったため直接最大幅を指定しています
=> [dashboard] Appsフィルターが画面内に収まらないときスクロールできるように

dashboard/package.json
Corepackのベストプラクティスに従うため (セキュリティ的な話だと思う)
`npx corepack use yarn@4.1.1` した
なし (強いて言うならYarnのアプデ)
=> chore: package.json の packageManager フィールドにsha512ハッシュを足した

pkg/domain/app_website.go, pkg/domain/app_website_test.go
close #923
ドメイン名から日本語文字を弾くため
半角英字と数字、ドット(.)以外の文字を弾くようにした
大文字を弾く処理をそのまま残したこと
-> エラーは一括で出るよりも細かく出たほうがいいと思うので、敢えて残しました
特になし
=> ドメイン名に半角英数字を弾く正規表現を追加した

dashboard/src/pages/apps/new.tsx
close #911
アプリケーション登録画面で、登録処理中にボタンを押せないように
特になし
他のところと違う実装方法なんですが、分からなかったのでとりあえずこういう形で実装してみました
もっと良い実装方法があれば教えて欲しいです
=> fix: アプリケーション登録画面で、登録処理中にボタンを押せないように

Dockerfile
Dockerfile 内の 'FROM' と 'AS' の大文字、小文字をそろえることが推奨されるようになった
https://docs.docker.com/reference/build-checks/from-as-casing/
'as'を'AS'にした
=> Dockerfile 内の 'as' を 'AS' にする

go.mod, pkg/usecase/builder/build_buildkit.go, pkg/usecase/builder/build_static.go
`SolveOpt` の `LocalDirs` の使用が非推奨のため
https://pkg.go.dev/github.com/moby/buildkit/client#SolveOpt
代わりに `LocalMounts` を使う
=> fix: use LocalMounts in buildkit SolveOpt

dashboard/src/components/templates/build/RuntimeImageRow.tsx, dashboard/src/pages/apps/[id]/builds/[id].tsx
close #921
ビルド結果のページでRuntimeアプリのイメージサイズを見られるようにする
StaticアプリのArtifactと同じ位置に表示するようにしました
=> Runtimeアプリのイメージサイズをダッシュボードから見られるようにする

pkg/infrastructure/grpc/api_app_service.go, pkg/usecase/apiserver/app_service.go
実装のミスにより、他人のリポジトリからアプリを作ったときに、アプリ作成者がオーナーにならないようになっていた
問題の修正
=> 他人のリポジトリからアプリを作ったときに、アプリ作成者がアプリオーナーになるように

dashboard/src/features/application/schema/websiteSchema.ts
バグ修正
h2c (= false) と httpPort (= 80) のデフォルト値を送信するように
N/A
N/A
=> Static App の URL がアップデートできなかったバグを修正

dashboard/src/components/templates/app/ContainerLogExport.tsx
close #987
SSIA + 若干のエラーハンドリング改善
根本的な原因: `fromJsonString` で  `2024-01-01T00:00:00.000Z` をパースしようとしているが、内部で `JSON.parse` が呼ばれていて、それがコケる
エラー時にダイアログの後ろにトーストが表示されてしまう現象の改善
=> 正しくログを出力できるように

dashboard/src/components/templates/app/AppDeployInfo.tsx, dashboard/src/components/templates/app/AppStatusIcon.tsx, dashboard/src/components/templates/app/AppsFilter.tsx, dashboard/src/libs/application.tsx, dashboard/src/pages/apps.tsx
- Sleep状態が(なぜか)表示できていなさそうだったので、表示した
- Idleと見分けるため、色は意図的に変えている 他と被らない紫に適当にした
- Filter部分にアプリとリポジトリ数のカウントを表示
変なところがあれば教えてもらえると助かります 🙇
=> dashboard: Sleepを表示 / Filter部分にカウントを表示

dashboard/src/features/application/components/form/website/WebsiteFieldGroup.tsx
feedback で特定の条件のみ、 URL delete ボタンで windowclose 関数が発動していた
fix #999
特定の条件というのは、 app/{appId} の URL パスに対して新規ウィンドウでアクセスした場合のみ、
- JavaScriptによって開かれた場合
- 履歴が1つしかないトップレベルブラウジングコンテキストの場合
の発動条件のうち後者に該当してしまうため発火していた
https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-window-close
これ以外の場合は本来設定されていた関数が発動されていなかっただけなので想定は window を閉じることであるように見受けられるが、使用感や今回上がった feedback からそもそも閉じないほうが便利だと考えたので閉じる関数の廃止に至った
閉じないほうが便利そうだったので、その記述自体を削除した
特になし
=> 不要な close 関数を削除した

dashboard/vite.config.mts
`ns.local.trapti.tech` に繋げないから
タイトル通り
=> added "ns.local.trapti.tech" to vite config

dashboard/src/components/templates/build/BuildStatusIcon.tsx
QUQUED/CANCELED/SKIPPED のアイコンが同じで区別しづらかったため
それぞれ別のアイコンにした
=> feat(dashboard): Build Status アイコンをより区別しやすいように

.github/workflows/ci.yaml, .golangci.yml
golangci-lintが動いてなかったので、更新する
http://github.com/traPtitech/NeoShowcase/actions/runs/14029523999/job/39274062277
> /home/runner/work/_temp/0f63b566-cc1c-472e-a199-d774f13741ab.sh: line 1: golangci-lint: command not found
=> update CI configuration and golangci-lint settings

cmd/wire_gen.go, pkg/usecase/builder/service.go
#1022 で builder作成時に必要なssh keyを、ローカルから取得するようにしてしまったので、ns-controllerのものを使うように挙動を元に戻す。
直した
本来はDIにより外部からgit serviceを注入したいが、keyはns-controller client作成後にしか取得できないので、今回は実行時にgit serviceを作成するようにした。
=> builder作成時に必要なssh keyをns-controllerから受け取るように修正

dashboard/src/features/application/components/form/general/BranchField.tsx
UX向上のため
SSIA
なし
ブランチが真に存在しない場合に変な挙動を示す可能性があるが、普通に使っている時にそうはならないので無視する
=> fix: ブランチが存在しないエラーの擬陽性を排除

dashboard/src/features/application/components/form/CreateAppForm.tsx
fix #1036
`<GeneralStep>` を常にマウントするようにした
原因は modular-forms の component が unmount されたことによって `formStore.form.config.deployConfig.type` が undefined になってしまっていたことだと思われる
=> fix: アプリ作成時にポート指定できないバグを修正

dashboard/src/components/UI/TextField.tsx, dashboard/src/components/templates/CheckBox.tsx, dashboard/src/components/templates/Header.tsx, dashboard/src/components/templates/RadioGroups.tsx
fix #819
- TextField のコピーボタン / RadioGroups / Checkbox に focus outline を付けた
- Header の button にフォーカスできないようにした
その他コンポーネントのフォーカス周りの改善
=> フォーカス周りの改善

.golangci.yml, cmd/providers.go, pkg/infrastructure/buildpack/backend.go, pkg/infrastructure/grpc/buildpack_helper_service_client.go, pkg/infrastructure/grpc/controller_service.go, pkg/infrastructure/grpc/token_auth_interceptor.go, pkg/infrastructure/log/victorialogs/streamer.go, pkg/infrastructure/log/victorialogs/types.go, pkg/infrastructure/repository/repository_commit.go, pkg/infrastructure/webhook/gitea.go, pkg/usecase/gitea-integration/integration.go, pkg/usecase/systeminfo/service.go, pkg/util/ds/slice_test.go, pkg/util/tarfs/extract.go
formatの形式をそろえておく。vscodeでのデフォルトにしておいた。
golangci-lintでformatterを指定
=> golangci-lintでformatterを指定

dashboard/src/features/application/components/form/CreateAppForm.tsx, dashboard/src/features/application/components/form/EnvVarConfigForm.tsx, dashboard/src/features/application/components/form/GeneralStep.tsx, dashboard/src/features/application/components/form/config/EnvVarConfigField.tsx, dashboard/src/features/application/provider/applicationFormProvider.tsx, dashboard/src/features/application/provider/envVarConfigFormProvider.tsx, dashboard/src/features/repository/provider/repositoryFormProvider.tsx, dashboard/src/pages/apps/[id]/settings/envVars.tsx, dashboard/src/pages/apps/new.tsx
Closes: #1058 
- `EnvVarConfigForm` の Field 部分を `EnvVarConfigField` として分離
- `stripEnvVars` を `EnvVarConfigField` 下に移動
- `FormStore<EnvVarInput>` を Context で与える形式に変更
- `GeneralStep` に `EnvVarConfigField` を追加
- `CreateAppForm` の `handleSubmit` に `setEnvVar` の call を追加
- 「今すぐ起動する」の初期値を `true` に変更
- アプリケーション作成時の環境変数設定欄には「Discard Changes」がないので，消去が少々手間．全消去ボタンや各行に破棄ボタンを設けてもよいかもしれない．
=> Feature: アプリケーション作成時に環境変数を設定できるようにする

pkg/infrastructure/backend/k8simpl/helper.go
現在の実装だとresourceのsyncに失敗したときに処理を終了するようになっているため、ひとつのsyncに失敗すると他もsyncされないようになっている
syncに失敗したらログだけ出してcontinueするようにした
=> fix: improve error handling in syncResources by logging and continuing on patch/delete failures

pkg/infrastructure/backend/k8simpl/helper.go
statefulsetには変更不可なフィールドがあるため、デプロイ時には削除してから再作成するようにしている。しかし、削除は非同期で行われるため、削除しきる前に変更不可フィールドを変更しようとしてエラーになることがあった。
リソースが削除されたことを確認できるまで待つようにした
=> StatefulSet置き換え処理の修正

pkg/infrastructure/backend/k8simpl/helper.go, pkg/infrastructure/backend/k8simpl/synchronize.go
#1090 で修正したつもりだったが、リソースが削除されたかの確認にpollingを使う実装だとRate Limitに引っかかってしまった
```
time="2025-08-07T08:50:41Z" level=error msg="failed to replace statefulsets/nsapp-a27937f8d6b9f224fcbff8" error="waiting for nsapp-a27937f8d6b9f224fcbff8/695551d624ea1e5a to be deleted: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"
```
pollingをやめ、watch APIを使い、リソースの削除を監視する
=> リソース置き換えの修正

.local-manifest/ns-system/values.yaml, charts/neoshowcase/templates/builder/deployment.yaml, charts/neoshowcase/templates/controller/deployment.yaml, charts/neoshowcase/templates/dashboard/deployment.yaml, charts/neoshowcase/templates/gateway/deployment.yaml, charts/neoshowcase/templates/gitea-integration/stateful-set.yaml, charts/neoshowcase/templates/sablier/deployment.yaml, charts/neoshowcase/templates/ssgen/stateful-set.yaml, charts/neoshowcase/values.yaml
手元でk3dを使って開発をする際、imagePullPolicyがAlwaysだと、手元でビルドしたものではなく、registryの最新のイメージをpullして使用してしまうため。
imagePullPolicyを設定できるようにした
=> feat(helm): make imagePullPolicy configurable for ns components
