traPtitech/NeoShowcase

pkg/memberchecker/authenticator.go
- リクエストのCookieのext_traP_tokenを見て、部員だったら200 OKとX-Showcase-Userを返す
=> add memberchecker

go.mod, pkg/dbmanager/mongo_impl.go, pkg/dbmanager/mongo_impl_test.go
- `mongo_impl_test.go`の実装
- `Create()`関数の実装
- `Delete()`関数の実装
close #13
=> MongoDBの操作を実装

go.mod, pkg/dbmanager/mariadb_impl.go, pkg/dbmanager/mariadb_impl_test.go
- MariaDBManager /pkg/dbmanager/mariadb_impl.go の `Create` と `Delete` を実装
- /pkg/dbmanager/mariadb_impl_test.go のtest実装
close #12
=> MariaDBManagerの実装

pkg/dbmanager/mariadb_impl_test.go
- TestMariaDBManagerImpl_Deleteでデータベースを作成してから削除するようにしました
close #27
=> TestMariaDBManagerImpl_Delete修正

pkg/appmanager/app_impl.go
app.m.builder.StartBuildStaticを用いて実装
close #34
=> buildtypeがstaticなアプリのRequestBuildの実装

pkg/apiserver/httpserver/webhook/gitea.go, pkg/apiserver/httpserver/webhook/github.go, pkg/apiserver/httpserver/webhook/receiver.go
- 受け取るURLをHTMLURLからCloneURLに変更
- 間違えていたTrimの修正
=> webhookの修正

pkg/builder/task.go
=> #26 旧showcase.yamlイメージビルド対応 

pkg/builder/task.go
=> buildImageのエラーハンドリングを修正

.github/workflows/ci.yaml
refs: https://github.com/traPtitech/NeoShowcase/issues/210
=> 💚  setup protoc actions

cmd/ns/wire_gen.go, pkg/usecase/app_deploy_service.go
=> set env vars on container create

go.mod, go.sum, pkg/usecase/cleaner_service.go
=> fix: prune deleted app images, fix delete manifest

dashboard/src/pages/apps.tsx
=> fix: JSXElement -> JSX.Element

pkg/domain/dbmanager.go, pkg/domain/environment.go, pkg/infrastructure/dbmanager/mariadb.go, pkg/infrastructure/dbmanager/mongodb.go, pkg/usecase/api_server_service.go
僕が直したのは、pkg/domain/environment.go の部分だけなので、
pkg/usecase/api_server_service.go の部分とそこにかかわる場所の実装をお願いします。
=> データーベースのEnvにHostが無かったので追加

.local-dev/config/ns.yaml, cmd/ns/main.go, cmd/ns/wire_gen.go, pkg/domain/app.go, pkg/domain/app_test.go, pkg/domain/backend.go, pkg/domain/backend_test.go, pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/dockerimpl/list_containers_test.go, pkg/infrastructure/backend/dockerimpl/runtime_ingress.go, pkg/infrastructure/backend/dockerimpl/synchronize.go, pkg/infrastructure/backend/dockerimpl/synchronize_ss.go, pkg/infrastructure/backend/dockerimpl/synchronize_test.go, pkg/infrastructure/backend/k8simpl/backend.go, pkg/infrastructure/backend/k8simpl/runtime_ingress.go, pkg/infrastructure/backend/k8simpl/synchronize.go, pkg/infrastructure/backend/k8simpl/synchronize_ss.go, pkg/infrastructure/backend/k8simpl/synchronize_test.go, pkg/usecase/app_deploy_helper.go
=> allow acquisition of wildcard certificates

.local-dev/config/ns.yaml, cmd/ns/main.go, cmd/ns/wire_gen.go, pkg/domain/app.go, pkg/domain/backend.go, pkg/domain/backend_test.go, pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/dockerimpl/backend_test.go, pkg/infrastructure/backend/dockerimpl/runtime_ingress.go, pkg/infrastructure/backend/dockerimpl/synchronize.go, pkg/infrastructure/backend/dockerimpl/synchronize_runtime.go, pkg/infrastructure/backend/dockerimpl/synchronize_ss.go, pkg/infrastructure/backend/k8simpl/backend.go, pkg/infrastructure/backend/k8simpl/runtime_ingress.go, pkg/infrastructure/backend/k8simpl/synchronize.go, pkg/infrastructure/backend/k8simpl/synchronize_runtime.go, pkg/infrastructure/backend/k8simpl/synchronize_ss.go, pkg/usecase/app_deploy_helper.go, pkg/util/ds/slice.go
=> recursive wildcard certs / allow picking wildcard domains

pkg/usecase/api_server_service.go
=> allow anyone to create app from public repo

pkg/domain/app.go, pkg/domain/app_test.go, pkg/domain/backend.go, pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/k8simpl/backend.go, pkg/usecase/api_server_service.go
=> better validation message handling

pkg/domain/app.go, pkg/domain/app_test.go, pkg/interface/repository/application.go, pkg/usecase/api_app_service.go, pkg/usecase/api_service.go
=> allow website path overlay only if owner

dashboard/package.json, dashboard/src/components/AppNav.tsx, dashboard/src/components/BuildStatusIcon.tsx, dashboard/src/components/Button.tsx, dashboard/src/components/Card.tsx, dashboard/src/components/Log.tsx, dashboard/src/components/RepositoryRow.tsx, dashboard/src/components/StatusIcon.tsx, dashboard/src/libs/application.tsx, dashboard/src/libs/buffers.ts, dashboard/src/libs/format.tsx, dashboard/src/libs/layout.tsx, dashboard/src/libs/sleep.ts, dashboard/src/pages/apps.tsx, dashboard/src/pages/apps/[id].tsx, dashboard/src/pages/apps/[id]/builds.tsx, dashboard/src/pages/apps/[id]/builds/[id].tsx, dashboard/src/routes.tsx, dashboard/yarn.lock
=> temporary view of dashboard

dashboard/src/pages/apps/[id].tsx, dashboard/src/pages/apps/[id]/builds/[id].tsx, pkg/infrastructure/log/loki/streamer.go, pkg/usecase/api_app_config_service.go
𝑔𝑟𝑎𝑐𝑒𝑓𝑢𝑙なhandlingをする
https://connect.build/docs/web/errors/
=> stream関連の修正

dashboard/src/components/Button.tsx, dashboard/src/pages/apps/[id].tsx
repository(に紐づくapp)のcommitをrefreshする機能を #518 でつけたから
appの詳細にrefreshボタンを適当に追加した
=> refresh repo button

dashboard/src/components/Modal.tsx, dashboard/src/libs/api.ts, dashboard/src/pages/apps/[id].tsx, dashboard/src/pages/repos/[id].tsx
=> add delete app button

.local-dev/config/ns-controller.yaml, .local-dev/config/ns-ssgen.yaml, .local-dev/manifest/ns-system/components/ssgen-deployment.yaml, .local-dev/manifest/ns-system/config/ns-ssgen.yaml, cmd/ns-ssgen/config.go, cmd/ns-ssgen/main.go, cmd/ns-ssgen/server.go, cmd/ns-ssgen/wire.go, cmd/ns-ssgen/wire_gen.go, docker-compose.yaml, pkg/domain/ssgen.go, pkg/infrastructure/staticserver/builtin.go, pkg/infrastructure/staticserver/builtin/server.go, pkg/infrastructure/staticserver/caddy/server.go, pkg/usecase/healthcheck/healthcheck.go, pkg/usecase/ssgen/generator.go
- add healthcheck
- (breaking) better structured config
- add caddy support
=> improve ssgen

pkg/infrastructure/grpc/api_app_service.go, pkg/util/optional/of.go
nilを指定されていない形として扱いたかったが、普通に書き方を間違えていた
=> fix nil slice being treated improperly

dashboard/src/pages/apps/[id]/settings.tsx
=> fix(dashboard): load runtime config on edit

dashboard/src/pages/settings.tsx, dashboard/src/routes.tsx
=> ユーザー設定画面の作成

dashboard/src/components/PortPublications.tsx, pkg/infrastructure/grpc/pbconvert/application.go, pkg/infrastructure/grpc/pbconvert/port_publication.go
=> fix: include ports in response

pkg/usecase/builder/build_buildkit.go
dockerfile2llbの第2返り値にはimageのconfig（entrypoint, command. workingdirなどの設定）が含まれているため、これをbuildkitに渡さないとその情報が失われてしまう
=> fix runtime config build: pass attributes from dockerfile2llb

pkg/domain/backend.go, pkg/infrastructure/backend/dockerimpl/exec.go, pkg/infrastructure/backend/dockerimpl/synchronize_runtime.go, pkg/infrastructure/backend/k8simpl/exec.go, pkg/usecase/sshserver/ssh_server.go
- k8s backend: requires new role binding: `pods/attach`
resolves #642
=> impl attach to container

dashboard/package.json, dashboard/src/components/AppsNew.tsx, dashboard/src/components/BuildConfigs.tsx, dashboard/src/components/Button.tsx, dashboard/src/components/IconButton.tsx, dashboard/src/components/InfoTooltip.tsx, dashboard/src/components/Input.tsx, dashboard/src/components/PortPublications.tsx, dashboard/src/components/Select.tsx, dashboard/src/components/WebsiteSettings.tsx, dashboard/src/global-style.ts, dashboard/src/index.tsx, dashboard/src/pages/apps/[id].tsx, dashboard/src/pages/apps/[id]/builds/[id].tsx, dashboard/src/pages/apps/[id]/settings.tsx, dashboard/src/pages/apps/new.tsx, dashboard/src/pages/repos/[id].tsx, dashboard/src/pages/repos/[id]/settings.tsx, dashboard/src/pages/settings.tsx, dashboard/yarn.lock
resolves #672 
- infoアイコンをいたるところにつけた (正直暫定の意味もある)
- selectを実装
- 一部UIを改善 (website, port forwarding設定)
=> たくさんアイコンをつける / UI改善

dashboard/src/components/AppMetrics.tsx
=> Appのmetricsを一定間隔で更新する #694

cmd/ns-controller/config.go, pkg/infrastructure/backend/k8simpl/config.go, pkg/infrastructure/backend/k8simpl/synchronize_runtime.go
resolve https://github.com/traPtitech/NeoShowcase/issues/720
XXH3Hashを利用してappIDから配置ホストを決定するようにした
https://q.trap.jp/messages/75d88573-25be-42d2-8e71-ce97af31ec09
=> feat: 🎸 pod schedulingの管理

cmd/wire_gen.go, pkg/usecase/apiserver/app_service.go, pkg/usecase/gitea-integration/integration.go, pkg/usecase/gitea-integration/sync.go, pkg/util/ds/slice.go
=> アプリ作成時に所有者をコピー / Gitea syncで所有者を追加

pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/k8simpl/backend.go, pkg/usecase/builder/service.go, pkg/usecase/ssgen/generator.go, pkg/util/retry/retry.go
=> Improve backend watch retry

dashboard/src/components/templates/app/ContainerLogExport.tsx
=> fix dl logs: scan entire days, show progress

.local-manifest/ns-system/kustomization.yaml
=> add buildpack address

dashboard/src/pages/apps/new.tsx
=> リポジトリ選択のレイアウトを改善

dashboard/src/components/templates/app/AppBranchResolution.tsx, dashboard/src/libs/api.ts, dashboard/src/libs/application.tsx, pkg/usecase/apiserver/repository_service.go, pkg/usecase/commit-fetcher/service.go, pkg/usecase/repofetcher/service.go
- error commit の内部状態になったときに内容のfetchが上手くいっていなかった
- error commit の内部状態になったものをgatewayで返していた
- error commit (000...000) の内部状態をエラーとして表示するように
=> commit表示に関する修正

.local-dev/config/ns.yaml, cmd/config.go, cmd/providers.go, cmd/wire_gen.go, pkg/usecase/builder/build.go, pkg/usecase/builder/service.go
=> Add builder timeout

pkg/usecase/builder/build_buildkit.go
close #952
Dockerfileのビルド前にエラーが発生した場合、build logを表示する処理が終わらなくなっていたのを修正
(`solveDockerfile`関数に渡される`ch`がreturn時にcloseされているようにする)
=> Runtimeアプリのビルド設定で、存在しないディレクトリをContextに指定するとbuilderがハングするのを修正

dashboard/src/features/application/schema/websiteSchema.ts
https://github.com/traPtitech/NeoShowcase/pull/984#discussion_r1884377764
リファクタリング
=> valibot 周りのちょっとしたリファクタリング

pkg/infrastructure/backend/k8simpl/backend.go
sablierの設定で enable: false としていてもenableになっていた
直した
=> fix: 'enable' field of sablier config was not working

dashboard/src/libs/application.tsx, pkg/domain/backend.go
exit 0 では適切にアプリが終了しており、エラーではない
タイトルの通り + Goのコードにドキュメントを書く
=> Exit code 0 の container をエラーと表示しない

.local-dev/config/ns.yaml, cmd/config.go, compose.yaml, pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/dockerimpl/config.go, pkg/infrastructure/backend/dockerimpl/ingress.go, pkg/infrastructure/backend/dockerimpl/synchronize_runtime.go, pkg/infrastructure/backend/dockerimpl/synchronize_ss.go
close #961
dockerでsablierを使ったランタイムアプリの自動停止機能の実装をした。
=> docker backend: sablier によるランタイムアプリの自動停止機能の実装

dashboard/src/features/application/schema/portPublicationSchema.ts
https://q.trap.jp/messages/01947807-46d7-7ca3-8b18-9c71cd3405d6
タイトル通り
なし
=> fix(dashboard): ポート公開の validation を修正

.golangci.yml, cmd/gitea-integration/server.go, cmd/providers.go, cmd/wire.go, pkg/infrastructure/backend/dockerimpl/backend.go, pkg/infrastructure/backend/dockerimpl/list_containers.go, pkg/infrastructure/backend/dockerimpl/synchronize_runtime.go, pkg/infrastructure/backend/k8simpl/backend_test.go, pkg/infrastructure/dbmanager/mongodb.go, pkg/infrastructure/grpc/buildpack_helper_service.go, pkg/infrastructure/repository/application.go, pkg/infrastructure/repository/git_repository.go, pkg/infrastructure/repository/runtime_image.go, pkg/usecase/builder/mock/builder.go, pkg/usecase/sshserver/ssh_server.go, pkg/util/tarfs/compress.go
#1020 で golangci-lint が動くようになったので、その時出たエラーに対応した。
=> lint error の修正

pkg/domain/app_test.go, pkg/infrastructure/backend/dockerimpl/ingress.go, pkg/infrastructure/backend/dockerimpl/list_containers_test.go, pkg/infrastructure/backend/dockerimpl/synchronize_ss.go, pkg/infrastructure/backend/k8simpl/backend_test.go, pkg/usecase/builder/state.go, pkg/usecase/ssgen/generator.go, pkg/util/cli/config.go, pkg/util/cli/print_conf.go, pkg/util/ds/map.go, pkg/util/ds/mutex_test.go, pkg/util/random/random.go, pkg/util/random/random_test.go
run `golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize -fix ./...`
=> refactor: Simplify code by using golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize

dashboard/src/pages/apps.tsx
=> fix: 検索結果が0件の時のスタイル崩れを修正

dashboard/package.json, dashboard/src/components/templates/OwnerList.tsx, dashboard/src/features/application/components/form/RepositoryStep.tsx, dashboard/src/libs/branchesSuggestion.ts, dashboard/src/pages/apps.tsx, dashboard/yarn.lock
fix #809
fuse.js の代わりに単純な (連続) 部分文字列のマッチで取るようにした
検索パフォーマンスの懸念があるが、実測したところレンダリングの負荷の方が大きそうだった
=> chore: fuse.js を単純な実装に置き換えた

dashboard/package.json, dashboard/src/features/application/components/form/CreateAppForm.tsx, dashboard/src/features/application/components/form/config/deploy/RuntimeConfigField.tsx, dashboard/src/features/application/schema/applicationSchema.ts, dashboard/yarn.lock
fix #1043
DB部分の `setValues` を `setValue` に書き換えた
根本原因の追究
=> fix: modular-forms 2.5.1 で起こるバグを修正

Makefile, buf.gen.go.yaml, buf.gen.ts.yaml, dashboard/package.json, dashboard/yarn.lock, go.mod, go.sum
pluginのバージョン管理をdependabotで行えるようにするため
go toolやyarn --devでpluginを管理するようにした
=> use local protoc plugins

.local-manifest/monitor/victoria-metrics/cluster-role-binding.yaml
=> fix(manifest/victoria-metrics): fix namespace

pkg/test/testhelper/mariadb.go
`container.Exec`でデータベースを作成しても、その後のmigrationで`unknown database`というエラーが出てしまうことがあった。これにより、CIのテストがたまに落ちてしまう。
Goのsql packageを使ってデータベースを作成するようにした
これで直ればok
=> testhelperでのデータベース作成処理の修正
